Homework/viewsresources 01
Otus-GPB/ViewResources pull request #6
Opened 2022-09-19 11:00 UTC by Zanozaroom

2022-10-02 17:42 UTC, antonkazakov requested changes
Привет. Твоя верстка отличается от макетов в Фигме, не совпадают цвета текста, размеры, есть дивайдеры на 2 экране. 
Диалог реализуй пожалуйста тоже через Constraint

2022-10-16 07:56 UTC, antonkazakov requested changes
Привет. Визуально все ок, цвета/темы/стили неправильно организованы, нужно поправить

2022-10-16 07:56 UTC, antonkazakov commented on app/src/main/res/values/colors.xml
> +    <color name="contacts_allfields_darkTheme">#272727</color>
А почему ты цвета не раскидала по notnight/night квалифаерам?

2022-10-16 07:56 UTC, antonkazakov commented on app/src/main/res/values/styles.xml
> +    <style name="contact_register" parent="TextAppearance.MaterialComponents.Button" >
Стили именуются через camelCase

2022-10-16 07:56 UTC, antonkazakov commented on app/src/main/res/values/styles.xml
> +    <style name="adapter_cart" parent="TextAppearance.MaterialComponents.Body1">
Что за это стиль? что за адаптер?

2022-10-16 07:56 UTC, antonkazakov commented on app/src/main/res/values/styles.xml
> +    <style name="textview_cart" parent="TextAppearance.MaterialComponents.Body2">
Не привязывай стиль к какой то фиче. Наверняка что то будет переиспользоваться. Давай им абстрактные названия Heading1, Caption2, Paragraph3 и т.п.

2022-10-16 07:56 UTC, antonkazakov commented on app/src/main/res/values/themes.xml
> +        <item name="windowActionBar">false</item>
В этом файле так много стилей что я даже не понял что происходит(
Здесь у тебя должныа быть описана "дневная" тема, в night квалифаере ночная тема и все.

2022-10-25 10:59 UTC, Zanozaroom commented on app/src/main/res/values/themes.xml
> +        <item name="windowActionBar">false</item>
Поняла тебя, раскидала стили для каждой активити в отдельные файлы и сделала отдельный файл для стиля диалога.

2022-10-25 11:02 UTC, Zanozaroom commented on app/src/main/res/values/colors.xml
> +    <color name="contacts_allfields_darkTheme">#272727</color>
Я цвета сделала общими, а темы раскидала по notnight/night. Цвета же могут использоваться и в других виджетах. Но вот тему основную из-за этого загрузила огромным кодом, раскидала оформление на разные файлы - каждому экрану своя тема.
Цвета переименовала, теперь это просто цвета, без каких-либо указателей на notnight/night

2022-11-20 09:41 UTC, closed without merging